# Generated by Django 4.0.3 on 2022-03-11 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False, unique=True, verbose_name='id num of user')),
                ('first_name', models.CharField(max_length=255, verbose_name='Name of user')),
                ('last_name', models.CharField(max_length=255, verbose_name='Surname of user')),
                ('email_address', models.CharField(max_length=255, unique=True, verbose_name='Email address of user')),
                ('phone', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Text of message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sender of message')),
            ],
        ),
    ]
