# Generated by Django 4.0.3 on 2022-03-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_site', '0002_alter_visitor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone number'),
        ),
    ]
